<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.0.0 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php 11423 2008-07-24 17:26:05Z lem9 $
 * Date: Mon, 27 Oct 2008 23:54:54 GMT
 */

/* Servers configuration */
$i = 0;

/* Server Kendoka (config:root) [1] */
$i++;
$cfg['Servers'][$i]['host'] = 'uwkc.ovid.u.washington.edu';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['port'] = '34422';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'pantheon';
$cfg['Servers'][$i]['verbose'] = 'Kendoka';

/* End of servers configuration */

?>
